# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Uiapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1046, 781)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_main = QtWidgets.QWidget(self.centralwidget)
        self.widget_main.setObjectName("widget_main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_main)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vertical_frame_panel = QtWidgets.QFrame(self.widget_main)
        self.vertical_frame_panel.setMinimumSize(QtCore.QSize(58, 0))
        self.vertical_frame_panel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.vertical_frame_panel.setStyleSheet("QWidget{\n"
"background-color : #1b1e23 ;\n"
"}\n"
"\n"
"\n"
"\n"
"QRadioButton{ \n"
"background-color :  transparent;\n"
"border : none ;\n"
"Text-align:left;\n"
"padding-left : 15px;\n"
"color : #858585;\n"
"font: 14px \"Poppins\";\n"
"\n"
" }\n"
"\n"
"QRadioButton:hover{\n"
" background-color: rgba(55,144,202 , 30);\n"
"\n"
"}\n"
"QRadioButton:checked{\n"
"color : white ; \n"
" background-color: rgba(55,144,202 , 30);\n"
"border-bottom: 0px;\n"
"border-top: 0px;\n"
"border-right: 0px;\n"
"border-left: 3px  solid #3790ca; \n"
"padding-left: 12px;\n"
"Text-align:left;\n"
"\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"width:0px;\n"
"height : 0px;\n"
"border-radius:0px;\n"
" }\n"
"")
        self.vertical_frame_panel.setObjectName("vertical_frame_panel")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.vertical_frame_panel)
        self.verticalLayout_5.setContentsMargins(0, 12, 0, 17)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logo_button = QtWidgets.QPushButton(self.vertical_frame_panel)
        self.logo_button.setMinimumSize(QtCore.QSize(40, 40))
        self.logo_button.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_button.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
" }")
        self.logo_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/icons8-school-96 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo_button.setIcon(icon1)
        self.logo_button.setIconSize(QtCore.QSize(40, 40))
        self.logo_button.setObjectName("logo_button")
        self.verticalLayout_5.addWidget(self.logo_button, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.upload_data_button = QtWidgets.QRadioButton(self.vertical_frame_panel)
        self.upload_data_button.setMinimumSize(QtCore.QSize(250, 50))
        self.upload_data_button.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.upload_data_button.setFont(font)
        self.upload_data_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload_data_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.upload_data_button.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/icons8-upload-to-the-cloud-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload_data_button.setIcon(icon2)
        self.upload_data_button.setIconSize(QtCore.QSize(20, 20))
        self.upload_data_button.setChecked(True)
        self.upload_data_button.setObjectName("upload_data_button")
        self.verticalLayout_5.addWidget(self.upload_data_button)
        self.run_reports_button = QtWidgets.QRadioButton(self.vertical_frame_panel)
        self.run_reports_button.setMinimumSize(QtCore.QSize(250, 50))
        self.run_reports_button.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.run_reports_button.setFont(font)
        self.run_reports_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_reports_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.run_reports_button.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/icons8-business-report-24 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_reports_button.setIcon(icon3)
        self.run_reports_button.setIconSize(QtCore.QSize(20, 20))
        self.run_reports_button.setChecked(False)
        self.run_reports_button.setObjectName("run_reports_button")
        self.verticalLayout_5.addWidget(self.run_reports_button)
        self.api_use_button = QtWidgets.QRadioButton(self.vertical_frame_panel)
        self.api_use_button.setMinimumSize(QtCore.QSize(250, 50))
        self.api_use_button.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.api_use_button.setFont(font)
        self.api_use_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.api_use_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.api_use_button.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/icons8-api-24 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.api_use_button.setIcon(icon4)
        self.api_use_button.setIconSize(QtCore.QSize(20, 20))
        self.api_use_button.setChecked(False)
        self.api_use_button.setObjectName("api_use_button")
        self.verticalLayout_5.addWidget(self.api_use_button)
        self.user_settings_button = QtWidgets.QRadioButton(self.vertical_frame_panel)
        self.user_settings_button.setMinimumSize(QtCore.QSize(250, 50))
        self.user_settings_button.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.user_settings_button.setFont(font)
        self.user_settings_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.user_settings_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.user_settings_button.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/icons8-settings-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_settings_button.setIcon(icon5)
        self.user_settings_button.setIconSize(QtCore.QSize(20, 20))
        self.user_settings_button.setChecked(False)
        self.user_settings_button.setObjectName("user_settings_button")
        self.verticalLayout_5.addWidget(self.user_settings_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.vertical_frame_panel)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_main)
        self.stackedWidget.setStyleSheet("\n"
"\n"
"\n"
"QWidget{\n"
"\n"
"background-color : #2c313c;\n"
"font: 14px \"Poppins\";\n"
"color : white ; \n"
"\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: none;\n"
"    border-radius: 1px;\n"
"    background : rgba(120, 123, 128, 1)\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #3790ca;\n"
"}\n"
"\n"
"\n"
"QPushButton{ \n"
"background-color: #3790ca ;\n"
"border-radius: 5px;\n"
"color : white ;\n"
"border: none;\n"
"font: 14px \"Poppins\";\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"padding-right : 27px ;\n"
"padding-left : 27px ;\n"
" }\n"
"QPushButton:hover{\n"
"border: 1px solid white;\n"
"padding : 4px ;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.upload_data_page = QtWidgets.QWidget()
        self.upload_data_page.setObjectName("upload_data_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.upload_data_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget = QtWidgets.QWidget(self.upload_data_page)
        self.verticalWidget.setStyleSheet("QWidget{\n"
"background-color : #1b1e23 ;\n"
"border-radius: 5px;\n"
"}")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_4.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        self.label_2.setStyleSheet("color : white ;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.verticalWidget_3 = QtWidgets.QWidget(self.upload_data_page)
        self.verticalWidget_3.setStyleSheet("QWidget{\n"
"background-color : #1b1e23 ;\n"
"border-radius: 5px;\n"
"}")
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_9.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_4.setStyleSheet("color : white ;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(15)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.verticalWidget_3)
        self.verticalWidget_2 = QtWidgets.QWidget(self.upload_data_page)
        self.verticalWidget_2.setStyleSheet("QWidget{\n"
"background-color : #1b1e23 ;\n"
"border-radius: 5px;\n"
"}")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_7.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.verticalWidget_2)
        self.label_3.setStyleSheet("color : white ;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.horizontalLayout.addWidget(self.verticalWidget_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dateEdit = QtWidgets.QDateEdit(self.upload_data_page)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_3.addWidget(self.dateEdit)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.upload_pushButton = QtWidgets.QPushButton(self.upload_data_page)
        self.upload_pushButton.setObjectName("upload_pushButton")
        self.verticalLayout_11.addWidget(self.upload_pushButton)
        self.progressBar_2 = QtWidgets.QProgressBar(self.upload_data_page)
        self.progressBar_2.setMinimumSize(QtCore.QSize(0, 5))
        self.progressBar_2.setMaximumSize(QtCore.QSize(16777215, 5))
        self.progressBar_2.setStyleSheet("")
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_11.addWidget(self.progressBar_2)
        self.status_label = QtWidgets.QLabel(self.upload_data_page)
        self.status_label.setObjectName("status_label")
        self.verticalLayout_11.addWidget(self.status_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.upload_data_page)
        self.run_reports_page = QtWidgets.QWidget()
        self.run_reports_page.setObjectName("run_reports_page")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.run_reports_page)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout_14.setSpacing(20)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalWidget_4 = QtWidgets.QWidget(self.run_reports_page)
        self.verticalWidget_4.setStyleSheet("QWidget{\n"
"background-color : #1b1e23 ;\n"
"border-radius: 5px;\n"
"}")
        self.verticalWidget_4.setObjectName("verticalWidget_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalWidget_4)
        self.verticalLayout_15.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_5 = QtWidgets.QLabel(self.verticalWidget_4)
        self.label_5.setStyleSheet("color : white ;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_15.addWidget(self.label_5)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_15.addItem(spacerItem10)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(15)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem11)
        self.horizontalLayout_5.addWidget(self.verticalWidget_4)
        self.verticalWidget_5 = QtWidgets.QWidget(self.run_reports_page)
        self.verticalWidget_5.setStyleSheet("QWidget{\n"
"background-color : #1b1e23 ;\n"
"border-radius: 5px;\n"
"}")
        self.verticalWidget_5.setObjectName("verticalWidget_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalWidget_5)
        self.verticalLayout_17.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_6 = QtWidgets.QLabel(self.verticalWidget_5)
        self.label_6.setStyleSheet("color : white ;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_17.addWidget(self.label_6)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_17.addItem(spacerItem12)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(15)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_17.addLayout(self.verticalLayout_18)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem13)
        self.horizontalLayout_5.addWidget(self.verticalWidget_5)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.run_reports_page)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_6.addWidget(self.dateEdit_2)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_6.addLayout(self.verticalLayout_20)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.generate_report_pushButton = QtWidgets.QPushButton(self.run_reports_page)
        self.generate_report_pushButton.setObjectName("generate_report_pushButton")
        self.verticalLayout_21.addWidget(self.generate_report_pushButton)
        self.progressBar_3 = QtWidgets.QProgressBar(self.run_reports_page)
        self.progressBar_3.setMinimumSize(QtCore.QSize(0, 5))
        self.progressBar_3.setMaximumSize(QtCore.QSize(16777215, 5))
        self.progressBar_3.setStyleSheet("")
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setObjectName("progressBar_3")
        self.verticalLayout_21.addWidget(self.progressBar_3)
        self.status_label_2 = QtWidgets.QLabel(self.run_reports_page)
        self.status_label_2.setObjectName("status_label_2")
        self.verticalLayout_21.addWidget(self.status_label_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_21)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        self.verticalLayout_22.addLayout(self.verticalLayout_14)
        self.stackedWidget.addWidget(self.run_reports_page)
        self.api_use_page = QtWidgets.QWidget()
        self.api_use_page.setObjectName("api_use_page")
        self.stackedWidget.addWidget(self.api_use_page)
        self.user_settings_page = QtWidgets.QWidget()
        self.user_settings_page.setObjectName("user_settings_page")
        self.stackedWidget.addWidget(self.user_settings_page)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.widget_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "app"))
        self.upload_data_button.setText(_translate("MainWindow", "    Upload data"))
        self.run_reports_button.setText(_translate("MainWindow", "    Run reports"))
        self.api_use_button.setText(_translate("MainWindow", "    Api use"))
        self.user_settings_button.setText(_translate("MainWindow", "    User settings"))
        self.label_2.setText(_translate("MainWindow", "Group name 1"))
        self.label_4.setText(_translate("MainWindow", "Group name 2"))
        self.label_3.setText(_translate("MainWindow", "Group name 3"))
        self.upload_pushButton.setText(_translate("MainWindow", "Upload"))
        self.status_label.setText(_translate("MainWindow", "Uploading ..."))
        self.label_5.setText(_translate("MainWindow", "Group name 1"))
        self.label_6.setText(_translate("MainWindow", "Group name 2"))
        self.generate_report_pushButton.setText(_translate("MainWindow", "generate report"))
        self.status_label_2.setText(_translate("MainWindow", "Uploading ..."))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
